"""initial schema

Revision ID: 3f0f52dc8084
Revises: 
Create Date: 2026-09-14 11:55:29.635002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3f0f52dc8084'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=False),
    sa.Column('line', sa.Text(), nullable=False),
    sa.Column('engine_cc', sa.Integer(), nullable=False),
    sa.Column('segment', sa.Text(), nullable=False),
    sa.Column('list_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('availability', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_index(op.f('ix_catalog_items_brand'), 'catalog_items', ['brand'], unique=False)
    op.create_index(op.f('ix_catalog_items_segment'), 'catalog_items', ['segment'], unique=False)
    op.create_table('companies',
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('pipeline_runs',
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_hashes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_table('points_of_sale',
    sa.Column('point_of_sale_id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('point_of_sale_id')
    )
    op.create_index(op.f('ix_points_of_sale_company_id'), 'points_of_sale', ['company_id'], unique=False)
    op.create_table('advisors',
    sa.Column('advisor_id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('point_of_sale_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('daily_capacity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('raw_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['point_of_sale_id'], ['points_of_sale.point_of_sale_id'], ),
    sa.PrimaryKeyConstraint('advisor_id')
    )
    op.create_index(op.f('ix_advisors_active'), 'advisors', ['active'], unique=False)
    op.create_index(op.f('ix_advisors_company_id'), 'advisors', ['company_id'], unique=False)
    op.create_index(op.f('ix_advisors_point_of_sale_id'), 'advisors', ['point_of_sale_id'], unique=False)
    op.create_table('leads',
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('point_of_sale_id', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.Text(), nullable=True),
    sa.Column('phone_raw', sa.Text(), nullable=True),
    sa.Column('phone_normalized', sa.Text(), nullable=True),
    sa.Column('email_raw', sa.Text(), nullable=True),
    sa.Column('email_normalized', sa.Text(), nullable=True),
    sa.Column('city_raw', sa.Text(), nullable=True),
    sa.Column('city_normalized', sa.Text(), nullable=True),
    sa.Column('model_text_raw', sa.Text(), nullable=True),
    sa.Column('sku', sa.Text(), nullable=True),
    sa.Column('registration_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('campaign', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('normalization_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('record_hash', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('first_seen_run', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('last_seen_run', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['first_seen_run'], ['pipeline_runs.run_id'], ),
    sa.ForeignKeyConstraint(['last_seen_run'], ['pipeline_runs.run_id'], ),
    sa.ForeignKeyConstraint(['point_of_sale_id'], ['points_of_sale.point_of_sale_id'], ),
    sa.ForeignKeyConstraint(['sku'], ['catalog_items.sku'], ),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_index(op.f('ix_leads_channel'), 'leads', ['channel'], unique=False)
    op.create_index(op.f('ix_leads_city_normalized'), 'leads', ['city_normalized'], unique=False)
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_content_hash'), 'leads', ['content_hash'], unique=False)
    op.create_index(op.f('ix_leads_email_normalized'), 'leads', ['email_normalized'], unique=False)
    op.create_index(op.f('ix_leads_first_contact_at'), 'leads', ['first_contact_at'], unique=False)
    op.create_index(op.f('ix_leads_is_current'), 'leads', ['is_current'], unique=False)
    op.create_index(op.f('ix_leads_phone_normalized'), 'leads', ['phone_normalized'], unique=False)
    op.create_index(op.f('ix_leads_point_of_sale_id'), 'leads', ['point_of_sale_id'], unique=False)
    op.create_index(op.f('ix_leads_record_hash'), 'leads', ['record_hash'], unique=False)
    op.create_index(op.f('ix_leads_registration_at'), 'leads', ['registration_at'], unique=False)
    op.create_index(op.f('ix_leads_sku'), 'leads', ['sku'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('assignments',
    sa.Column('assignment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('advisor_id', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('point_of_sale_id', sa.Text(), nullable=True),
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('strategy_version', sa.Text(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.advisor_id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['point_of_sale_id'], ['points_of_sale.point_of_sale_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_assignments_advisor_id'), 'assignments', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_assignments_company_id'), 'assignments', ['company_id'], unique=False)
    op.create_index(op.f('ix_assignments_is_current'), 'assignments', ['is_current'], unique=False)
    op.create_index(op.f('ix_assignments_lead_id'), 'assignments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_assignments_point_of_sale_id'), 'assignments', ['point_of_sale_id'], unique=False)
    op.create_index(op.f('ix_assignments_run_date'), 'assignments', ['run_date'], unique=False)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('lead_id', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('messages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('first_seen_run', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('last_seen_run', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['first_seen_run'], ['pipeline_runs.run_id'], ),
    sa.ForeignKeyConstraint(['last_seen_run'], ['pipeline_runs.run_id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_conversations_company_id'), 'conversations', ['company_id'], unique=False)
    op.create_index(op.f('ix_conversations_content_hash'), 'conversations', ['content_hash'], unique=False)
    op.create_index(op.f('ix_conversations_lead_id'), 'conversations', ['lead_id'], unique=False)
    op.create_index(op.f('ix_conversations_started_at'), 'conversations', ['started_at'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_table('lead_scores',
    sa.Column('score_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('score_version', sa.Text(), nullable=False),
    sa.Column('priority_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('urgency_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('queue_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('band', sa.Text(), nullable=True),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('params_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_index(op.f('ix_lead_scores_band'), 'lead_scores', ['band'], unique=False)
    op.create_index(op.f('ix_lead_scores_is_current'), 'lead_scores', ['is_current'], unique=False)
    op.create_index(op.f('ix_lead_scores_lead_id'), 'lead_scores', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_scores_run_id'), 'lead_scores', ['run_id'], unique=False)
    op.create_index(op.f('ix_lead_scores_score_version'), 'lead_scores', ['score_version'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('advisor_id', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('admin_empresa', 'supervisor', 'asesor')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.advisor_id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_table('ai_extractions',
    sa.Column('extraction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.Text(), nullable=False),
    sa.Column('fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('extraction_id'),
    sa.UniqueConstraint('conversation_id', 'input_hash', name='uq_ai_extractions_conversation_input')
    )
    op.create_index(op.f('ix_ai_extractions_conversation_id'), 'ai_extractions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_extractions_is_current'), 'ai_extractions', ['is_current'], unique=False)
    op.create_index(op.f('ix_ai_extractions_status'), 'ai_extractions', ['status'], unique=False)
    op.create_table('identity_clusters',
    sa.Column('cluster_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('canonical_lead_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('match_strength', sa.Text(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('matched_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('decided_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_lead_id'], ['leads.lead_id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_index(op.f('ix_identity_clusters_canonical_lead_id'), 'identity_clusters', ['canonical_lead_id'], unique=False)
    op.create_index(op.f('ix_identity_clusters_company_id'), 'identity_clusters', ['company_id'], unique=False)
    op.create_index(op.f('ix_identity_clusters_status'), 'identity_clusters', ['status'], unique=False)
    op.create_table('identity_members',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=True),
    sa.Column('match_strength', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['identity_clusters.cluster_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'lead_id', name='uq_identity_members_cluster_lead')
    )
    op.create_index(op.f('ix_identity_members_cluster_id'), 'identity_members', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_identity_members_lead_id'), 'identity_members', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_members_lead_id'), table_name='identity_members')
    op.drop_index(op.f('ix_identity_members_cluster_id'), table_name='identity_members')
    op.drop_table('identity_members')
    op.drop_index(op.f('ix_identity_clusters_status'), table_name='identity_clusters')
    op.drop_index(op.f('ix_identity_clusters_company_id'), table_name='identity_clusters')
    op.drop_index(op.f('ix_identity_clusters_canonical_lead_id'), table_name='identity_clusters')
    op.drop_table('identity_clusters')
    op.drop_index(op.f('ix_ai_extractions_status'), table_name='ai_extractions')
    op.drop_index(op.f('ix_ai_extractions_is_current'), table_name='ai_extractions')
    op.drop_index(op.f('ix_ai_extractions_conversation_id'), table_name='ai_extractions')
    op.drop_table('ai_extractions')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lead_scores_score_version'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_run_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_lead_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_is_current'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_band'), table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_started_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_lead_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_content_hash'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_company_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_run_date'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_point_of_sale_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_lead_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_is_current'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_company_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_advisor_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_sku'), table_name='leads')
    op.drop_index(op.f('ix_leads_registration_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_record_hash'), table_name='leads')
    op.drop_index(op.f('ix_leads_point_of_sale_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone_normalized'), table_name='leads')
    op.drop_index(op.f('ix_leads_is_current'), table_name='leads')
    op.drop_index(op.f('ix_leads_first_contact_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_email_normalized'), table_name='leads')
    op.drop_index(op.f('ix_leads_content_hash'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_city_normalized'), table_name='leads')
    op.drop_index(op.f('ix_leads_channel'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_advisors_point_of_sale_id'), table_name='advisors')
    op.drop_index(op.f('ix_advisors_company_id'), table_name='advisors')
    op.drop_index(op.f('ix_advisors_active'), table_name='advisors')
    op.drop_table('advisors')
    op.drop_index(op.f('ix_points_of_sale_company_id'), table_name='points_of_sale')
    op.drop_table('points_of_sale')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_table('companies')
    op.drop_index(op.f('ix_catalog_items_segment'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_brand'), table_name='catalog_items')
    op.drop_table('catalog_items')
    # ### end Alembic commands ###
